extractors:
  - name: "log_mel"
    params:
      n_fft: 2048
      hop_length: 512
      n_mels: 80
      window: "hann"

  - name: "mfcc"
    params:
      n_fft: 2048
      hop_length: 512
      n_mels: 80
      n_mfcc: 40
      window: "hann"